server:
  port: 8082

spring:
  application:
    name: product-service

  security:
    oauth2:
      introspection-uri: http://localhost:8081/oauth2/introspect

  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: 19pool90

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: 'classpath:/db/changelog/liquibase.change-log.xml'

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
            allowedHeaders: "*"
            allowCredentials: true

  logging:
    level:
      root: INFO
      com.example.demo_resource_server: DEBUG
      org.springframework.jdbc: DEBUG
      org.springframework.security: trace

openapi:
  service:
    title: product-service doc
    version: 1.0.0
    url: http://127.0.0.1:8080

springdoc:
  api-docs:
    path: /product-service/v3/api-docs
  swagger-ui:
    path: /product-service/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: prometheus

resilience4j.circuitbreaker:
  instances:
    serviceB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
